"""empty message

Revision ID: 0d5bc1e7130f
Revises: e66b9b19bb30
Create Date: 2019-11-06 12:52:48.951088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d5bc1e7130f'
down_revision = 'e66b9b19bb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipath_namelist', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ipath_namelist', 'record',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipath_namelist', 'record',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ipath_namelist', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
