"""empty message

Revision ID: 506f6aa9b7c8
Revises: 25ff5af7c054
Create Date: 2019-11-11 12:05:32.412115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506f6aa9b7c8'
down_revision = '25ff5af7c054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipath_namelist', sa.Column('points', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipath_namelist', 'points')
    # ### end Alembic commands ###
