"""empty message

Revision ID: bd80217c8c2c
Revises: d555ba2b6e9a
Create Date: 2019-11-06 12:38:23.310795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd80217c8c2c'
down_revision = 'd555ba2b6e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipath_namelist',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nickname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipath_namelist')
    # ### end Alembic commands ###
