"""empty message

Revision ID: d555ba2b6e9a
Revises: 377a10b0e071
Create Date: 2019-11-06 11:55:33.590511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd555ba2b6e9a'
down_revision = '377a10b0e071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('comments', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
