"""empty message

Revision ID: e66b9b19bb30
Revises: bd80217c8c2c
Create Date: 2019-11-06 12:52:13.151666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66b9b19bb30'
down_revision = 'bd80217c8c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipath_namelist', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipath_namelist', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
